#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sm-db-1.0.0
Version  : 3ee0e6855958e9d702314f1577e619f657e79ffd
Release  : 1
URL      : https://github.com/openstack/stx-ha/archive/3ee0e6855958e9d702314f1577e619f657e79ffd.tar.gz
Source0  : https://github.com/openstack/stx-ha/archive/3ee0e6855958e9d702314f1577e619f657e79ffd.tar.gz
Summary  : Service Management Databases
Group    : Development/Tools
License  : Apache-2.0
Requires: sm-db-1.0.0-lib
BuildRequires : buildreq-distutils3
BuildRequires : gcc
BuildRequires : glib-dev
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : sm-common-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : tox
BuildRequires : util-linux-dev
BuildRequires : virtualenv
Patch1: 0001-disable-warning-as-error.patch
Patch2: 0002-reorder-LDLIBS.patch
Patch3: 0003-fix-comparison-between-pointer-and-char.patch

%description
Service Managment Databases

%package dev
Summary: dev components for the sm-db-1.0.0 package.
Group: Development
Requires: sm-db-1.0.0-lib
Provides: sm-db-1.0.0-devel

%description dev
dev components for the sm-db-1.0.0 package.


%package lib
Summary: lib components for the sm-db-1.0.0 package.
Group: Libraries

%description lib
lib components for the sm-db-1.0.0 package.


%prep
%setup -q -n stx-ha-3ee0e6855958e9d702314f1577e619f657e79ffd
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
## build_prepend content
pushd service-mgmt/sm-db-1.0.0
sqlite3 database/sm.db < database/create_sm_db.sql
sqlite3 database/sm.hb.db < database/create_sm_hb_db.sql
popd
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538157565
pushd service-mgmt/sm-db-1.0.0
make  %{?_smp_mflags} VER=${VER} VER_MJR=$MAJOR
popd

%install
## install_prepend content
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
## install_prepend end
export SOURCE_DATE_EPOCH=1538157565
rm -rf %{buildroot}
pushd service-mgmt/sm-db-1.0.0
make DEST_DIR=$RPM_BUILD_ROOT VER=$VER VER_MJR=$MAJOR install_non_bb
popd

%files
%defattr(-,root,root,-)
/var/lib/sm/patches/sm-patch.sql
/var/lib/sm/sm.db
/var/lib/sm/sm.hb.db

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libsm_db.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsm_db.so.3ee0e6855958e9d702314f1577e619f657e79ffd
